In [60]:
import pandas as pd
diamonds=pd.read_csv("diamonds.csv")
diamonds.head(10)

  carat        cut color clarity  depth  table  price     x     y     z
0  0.23      Ideal     E     SI2   61.5   55.0  326.0  3.95  3.98  2.43
1  0.21    Premium     E     SI1   59.8   61.0  326.0  3.89  3.84  2.31
2  0.23       Good     E     VS1   56.9   65.0  327.0  4.05  4.07  2.31
3  0.29    Premium     I     VS2   62.4   58.0  334.0  4.20  4.23  2.63
4  0.31       Good     J     SI2   63.3   58.0  335.0  4.34  4.35  2.75
5  0.24  Very Good     J    VVS2   62.8   57.0    NaN  3.94  3.96  2.48
6  0.24  Very Good     I    VVS1   62.3   57.0  336.0  3.95  3.98  2.47
7  0.26  Very Good     H     SI1   61.9   55.0  337.0  4.07  4.11  2.53
8  0.22       Fair     E     VS2   65.1   61.0  337.0  3.87  3.78  2.49
9  0.23  Very Good     H     VS1   59.4   61.0  338.0  4.00  4.05  2.39

Question_11

In [62]:
diamonds.duplicated().sum()

149

Question_12

In [64]:
diamonds=diamonds.dropna(subset=['carat','cut'])
diamonds.head(10)

  carat        cut color clarity  depth  table  price     x     y     z
0  0.23      Ideal     E     SI2   61.5   55.0  326.0  3.95  3.98  2.43
1  0.21    Premium     E     SI1   59.8   61.0  326.0  3.89  3.84  2.31
2  0.23       Good     E     VS1   56.9   65.0  327.0  4.05  4.07  2.31
3  0.29    Premium     I     VS2   62.4   58.0  334.0  4.20  4.23  2.63
4  0.31       Good     J     SI2   63.3   58.0  335.0  4.34  4.35  2.75
5  0.24  Very Good     J    VVS2   62.8   57.0    NaN  3.94  3.96  2.48
6  0.24  Very Good     I    VVS1   62.3   57.0  336.0  3.95  3.98  2.47
7  0.26  Very Good     H     SI1   61.9   55.0  337.0  4.07  4.11  2.53
8  0.22       Fair     E     VS2   65.1   61.0  337.0  3.87  3.78  2.49
9  0.23  Very Good     H     VS1   59.4   61.0  338.0  4.00  4.05  2.39

Question_13

In [66]:
numeric_diamonds=diamonds.select_dtypes(include=['number'])
numeric_diamonds.head(10)

   depth  table  price     x     y     z
0   61.5   55.0  326.0  3.95  3.98  2.43
1   59.8   61.0  326.0  3.89  3.84  2.31
2   56.9   65.0  327.0  4.05  4.07  2.31
3   62.4   58.0  334.0  4.20  4.23  2.63
4   63.3   58.0  335.0  4.34  4.35  2.75
5   62.8   57.0    NaN  3.94  3.96  2.48
6   62.3   57.0  336.0  3.95  3.98  2.47
7   61.9   55.0  337.0  4.07  4.11  2.53
8   65.1   61.0  337.0  3.87  3.78  2.49
9   59.4   61.0  338.0  4.00  4.05  2.39

Question_14

In [68]:
diamonds['volume']=diamonds.apply(lambda row:row['x']*row['y']*row['z'] if row['depth']>60 else 8,axis=1)
diamonds.head(20)

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.23,Ideal,E,SI2,61.5,55.0,326.0,3.95,3.98,2.43,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326.0,3.89,3.84,2.31,8.000000
2,0.23,Good,E,VS1,56.9,65.0,327.0,4.05,4.07,2.31,8.000000
3,0.29,Premium,I,VS2,62.4,58.0,334.0,4.20,4.23,2.63,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75,51.917250
5,0.24,Very Good,J,VVS2,62.8,57.0,NaN,3.94,3.96,2.48,38.693952
6,0.24,Very Good,I,VVS1,62.3,57.0,336.0,3.95,3.98,2.47,38.830870
7,0.26,Very Good,H,SI1,61.9,55.0,337.0,4.07,4.11,2.53,42.321081
8,0.22,Fair,E,VS2,65.1,61.0,337.0,3.87,3.78,2.49,36.425214
9,0.23,Very Good,H,VS1,59.4,61.0,338.0,4.00,4.05,2.39,8.000000
10,0.31,Good,J,SI2,63.3,58.0,335.0,4.34,4.35,2.75,51.917250
11,0.3,Good,J,SI1,64.0,55.0,339.0,4.25,4.28,2.73,49.658700
12,0.23,Ideal,J,VS1,62.8,56.0,340.0,3.93,3.90,2.46,37.704420
13,0.22,Premium,F,SI1,60.4,61.0,342.0,3.88,3.84,2.33,34.715136
14,0.31,Ideal,J,SI2,62.2,54.0,344.0,4.35,4.37,2.71,51.515745
15,'0.2',Premium,E,SI2,60.2,62.0,345.0,3.79,3.75,2.27,32.262375
16,0.32,Premium,E,I1,60.9,58.0,345.0,4.38,4.42,2.68,51.883728
17,0.3,Ideal,I,SI2,62.0,54.0,348.0,4.31,4.34,2.68,50.130472
18,0.3,Good,J,SI1,63.4,54.0,351.0,4.23,4.29,2.70,48.996090
19,0.3,Good,J,SI1,63.8,56.0,351.0,4.23,4.26,NaN,NaN

Question_15

In [86]:
diamonds['price'].isnull().sum()
mean_price=diamonds['price'].mean()
diamonds['price']=diamonds['price'].fillna(mean_price)
diamonds.head(20)

,carat,cut,color,clarity,depth,table,price,x,y,z,volume
0,0.23,Ideal,E,SI2,61.5,55.0,326.00000,3.95,3.98,2.43,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326.00000,3.89,3.84,2.31,8.000000
2,0.23,Good,E,VS1,56.9,65.0,327.00000,4.05,4.07,2.31,8.000000
3,0.29,Premium,I,VS2,62.4,58.0,334.00000,4.20,4.23,2.63,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335.00000,4.34,4.35,2.75,51.917250
5,0.24,Very Good,J,VVS2,62.8,57.0,3932.94564,3.94,3.96,2.48,38.693952
6,0.24,Very Good,I,VVS1,62.3,57.0,336.00000,3.95,3.98,2.47,38.830870
7,0.26,Very Good,H,SI1,61.9,55.0,337.00000,4.07,4.11,2.53,42.321081
8,0.22,Fair,E,VS2,65.1,61.0,337.00000,3.87,3.78,2.49,36.425214
9,0.23,Very Good,H,VS1,59.4,61.0,338.00000,4.00,4.05,2.39,8.000000
10,0.31,Good,J,SI2,63.3,58.0,335.00000,4.34,4.35,2.75,51.917250
11,0.3,Good,J,SI1,64.0,55.0,339.00000,4.25,4.28,2.73,49.658700
12,0.23,Ideal,J,VS1,62.8,56.0,340.00000,3.93,3.90,2.46,37.704420
13,0.22,Premium,F,SI1,60.4,61.0,342.00000,3.88,3.84,2.33,34.715136
14,0.31,Ideal,J,SI2,62.2,54.0,344.00000,4.35,4.37,2.71,51.515745
15,'0.2',Premium,E,SI2,60.2,62.0,345.00000,3.79,3.75,2.27,32.262375
16,0.32,Premium,E,I1,60.9,58.0,345.00000,4.38,4.42,2.68,51.883728
17,0.3,Ideal,I,SI2,62.0,54.0,348.00000,4.31,4.34,2.68,50.130472
18,0.3,Good,J,SI1,63.4,54.0,351.00000,4.23,4.29,2.70,48.996090
19,0.3,Good,J,SI1,63.8,56.0,351.00000,4.23,4.26,NaN,NaN

In [88]:
diamonds['price'].isnull().sum()

0